language: go
sudo: false
go:
  - 1.8
install:
  - go get github.com/vkuznet/x509proxy
  - go get github.com/buger/jsonparser
  - go get github.com/pkg/profile
  - go get github.com/rcrowley/go-metrics
  - go get github.com/zemirco/couchdb
  - go get github.com/segmentio/pointer
  - go get github.com/sirupsen/logrus
